//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.01 at 08:19:58 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://credable.io/cbs/transaction", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.credable.scoringmiddleware.service.soap.api.model;
